# File: drivers/char/ac49x_dsp/Makefile
#
# Makefile for the Linux ac49x dsp driver.
#

# File: drivers/char/ac49x_dsp/Makefile
#
# Makefile for the ac49x_dsp driver.
#
EXTRA_CFLAGS:=$(CUST_KCFLAGS)
#EXTRA_CFLAGS += $(CUST_INCDIR)


obj-m += gpiodrv.o
ac49x_dsp-objs := pal_vlynq.o pal_vlynqDev.o pal_vlynqIoctl.o gpiodrv.o

