RGSRC=../../../../../../
include $(RGSRC)/envir.mak
MOD_TARGET=mod_vp_api_lib_common.o
O_OBJS_mod_vp_api_lib_common.o=vp_api.o vp_api_common.o boot_common.o hbi_common.o
MOD_CFLAGS+=-I../includes -I../../arch/uvb/ -I./zlib121
include $(RGMK)
